const PLACES: string[] = [
  "Cinema",
  "Restaurant",
  "Park",
  "Beach",
  "Museum",
  "Theater",
  "Stadium",
  "Zoo",
  "Library",
  "Gym",
  "Bar",
  "Cafe",
  "Club",
  "Hotel",
  "Hospital",
  "School",
  "University",
  "Airport",
  "Bus station",
  "Train station",
  "Subway station",
  "Taxi stand",
  "Pharmacy",
  "Supermarket",
  "Shopping mall",
  "Bank",
  "ATM",
  "Post office",
  "Police station",
  "Fire station",
  "Parking",
  "Gas station",
  "Car repair",
  "Car wash",
  "Car rental",
  "Car dealer",
  "Furniture store",
  "Electronics store",
  "Clothing store",
  "Shoe store",
  "Jewelry store",
  "Pet store",
  "Toy store",
  "Book store",
  "Florist",
  "Liquor store",
  "Hardware store",
];

export default PLACES;
